-- The offline sales ledger: seats sold with no `Order` and no `Ticket` row
-- (ADR-0025). Two sources share one table because they are the same shape of
-- fact: `door` (cash or card taken at the entrance) and `legacy` (the old
-- WordPress/Tickera site, frozen at the 2026-06-07 cutover).
--
-- A RAW table, deliberately not a Payload collection (the rule that
-- `marketing_optouts`, `push_subscriptions` and the `oauth_*` tables already
-- follow): the only writer is `POST /api/shows/[id]/offline-sales`, entry has a
-- purpose-built UI, and nobody needs generic admin CRUD over a tally. Because
-- Payload's push never emits it, it must NOT appear in the generated
-- `00-base.sql` — the drift gate only requires the bootstrap schema to be a
-- SUPERSET of Payload's, so an extra table here is fine while a regeneration
-- would silently drop anything hand-added there.
--
-- ORDERING: bootstrap-db.mjs applies these files in plain filename order with
-- no dependency resolution (db/schema/README.md). The `-da-` is a SORT KEY, not
-- a word. It has to land after `migrate-zz-d-oauth.sql` ('-' 0x2d < 'a' 0x61)
-- and before `migrate-zz-drop-users-role.sql` ('a' 0x61 < 'r' 0x72), which must
-- stay the last `migrate-*` file (#398, asserted by `db-schema-safety.test.ts`).
-- The single-letter convention ran out at `d`, hence the two-character key.
-- Both FKs point at tables `00-base.sql` builds first on a fresh database and
-- that have existed on every populated one since the first deploy.
--
-- WHY A LEDGER AND NOT TWO MORE COUNTERS. `shows.in_person_sold` could hold a
-- headcount and nothing else: not the adult/child split, not the money, and not
-- the reason a seat cost less than face value. The 2026 season needed all
-- three — 53 of 704 door seats were children, and 32 were pensioners who paid
-- €15 under a group discount. A discounted seat is still an ADULT seat carrying
-- a discount, never a third price category; that is the whole point of
-- `discount_label` sitting next to `ticket_type` rather than inside it.
--
-- APPEND-ONLY. `quantity` may be negative: that is how a miscount is corrected,
-- by appending the inverse line rather than editing or deleting one, so the
-- error and its correction both stay visible. Nothing in the app ever UPDATEs
-- or DELETEs a row here.
--
-- Every statement is guarded and safe to re-run on every restart. Nothing here
-- writes or mutates a row.

-- 1. Which artifact-less channel the line came from.
DO $$ BEGIN
    CREATE TYPE public.enum_offline_sales_source AS ENUM ('door', 'legacy');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 2. The ledger itself.
--
--    `ticket_type` reuses `enum_tickets_type` rather than declaring a parallel
--    vocabulary: an offline seat is the same kind of thing as a ticketed seat,
--    so if the system ever gains a third type the ledger gains it for free.
--
--    `unit_price_cents` is the price ACTUALLY CHARGED, resolved at write time
--    and frozen here. Face-value lines copy the ADULT_PRICE_EUR /
--    CHILD_PRICE_EUR constants; a discounted line stores what was taken. The
--    constants stay the source of truth for what to charge, the ledger for what
--    was charged, so a future price change cannot rewrite 2026's books.
--
--    `discount_label` NULL means full price. A non-NULL label is the human
--    reason ('umirovljenici (grupni popust)'), shown wherever the line is.
--
--    ON DELETE CASCADE on the show: deleting a performance takes its tally with
--    it, matching how the order/ticket cascade already behaves.
--    ON DELETE SET NULL on the author: the line outlives the account that typed
--    it, and `created_by_id` is only ever provenance.
CREATE TABLE IF NOT EXISTS public.offline_sales (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id           integer NOT NULL REFERENCES public.shows(id) ON DELETE CASCADE,
    source            public.enum_offline_sales_source NOT NULL,
    ticket_type       public.enum_tickets_type NOT NULL,
    quantity          integer NOT NULL CHECK (quantity <> 0),
    unit_price_cents  integer NOT NULL CHECK (unit_price_cents >= 0),
    discount_label    varchar(120),
    note              varchar(255),
    created_by_id     integer REFERENCES public.users(id) ON DELETE SET NULL,
    created_at        timestamp with time zone NOT NULL DEFAULT NOW()
);

-- 3. Every read is "the lines of one performance", usually narrowed to one
--    source (the two cached counters on `shows` are per-source totals). One
--    composite index serves both shapes.
CREATE INDEX IF NOT EXISTS offline_sales_show_source_idx
    ON public.offline_sales (show_id, source);
