-- Seed the public /faq from the reviewed English drafts
-- (docs/faq-drafts/faq-answers-en.md). GENERATED — do not hand-edit;
-- regenerate with: npm run seed:faqs -- --emit-sql > db/schema/seed-faqs.sql
--
-- Idempotent (INSERT ... WHERE NOT EXISTS on question+locale): inserts each
-- answer once, never clobbers admin edits or re-adds a deleted row's counts.
-- 44 published, 1 draft (Q49 tour list, pending #340). EN only.
-- Sorts after 00-base.sql / migrate-faqs.sql (needs the faqs table).

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'What is the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška is a traditional sword dance from the town of Korčula, Croatia, in which two armies fight a series of staged battles with real iron swords over the fate of a captured woman. It combines spoken drama, a live brass orchestra, and seven escalating sword-clash figures, and it is widely described as ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Europe''s last surviving authentic war dance","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". In Korčula it has been documented since 1666 and performed by the local community ever since.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 0, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'What is the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška worth seeing?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška is the only sword dance of its kind still performed intact in Europe, with real iron swords, a live brass orchestra, and a story acted in archaic 17th-century verse. Similar dances once spanned the Mediterranean, from Spain to the Greek islands; Korčula is the last place it survives complete. For visitors it is loud, dramatic, and rooted in centuries of local identity, an experience that can''t be replicated anywhere else.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 1, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška worth seeing?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška protected?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška is officially recognised as a ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"protected cultural good of the Republic of Croatia","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", a status granted by the Ministry of Culture. The designation safeguards its traditional elements, the double-sword technique and the local-dialect dialogue, from commercial dilution and helps preserve them in authentic form.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 2, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška protected?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška a dance or a play?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"It is both, the Moreška is a \"syncretic\" performance that seamlessly combines a written drama with a sword dance. It opens as a play, with characters speaking in archaic 17th-century Korčulan verse, and then becomes a dance, as two armies fight seven choreographed sword battles.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 3, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška a dance or a play?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is there spoken or dramatic text?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, before the fighting begins, the characters speak a scripted dialogue written in an archaic 17th-century Korčulan dialect. This prologue sets up the conflict: the captured Bula declares her loyalty, and the challenge between the two kings is issued before the armies clash.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 4, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is there spoken or dramatic text?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška a symbol of Korčula?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška is regarded as the cultural symbol of Korčula and a symbol of Croatian intangible heritage. Passed from father to son for generations, it is so central to local identity that the town has a saying, ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"\"You are not a male if you cannot dance Moreška.\"","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'about'::enum_faqs_category, 'en'::enum_faqs_locale, 5, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška a symbol of Korčula?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Does the Moreška have main characters?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška has four main characters: the ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Bula","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (the captured maiden), ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Osman","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (the White King, her betrothed), ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Moro","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (the Black King, her abductor), and ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Otmanović","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (Moro''s father). Around them, two full armies, White and Black, fight the seven battles.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 6, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Does the Moreška have main characters?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Why do the kings fight in the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The two kings fight over a woman, the Bula, who has been abducted. Moro, the Black King, has taken the Bula by force and tries to win her love; Osman, the White King and her betrothed, comes to free her. The conflict is not only over the woman but over honour and the sanctity of marriage, and it is settled in seven sword battles.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 7, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Why do the kings fight in the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who is the Bula?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Bula is the captured maiden at the centre of the Moreška, the betrothed of the White King, Osman. She is taken by force by Moro, the Black King, and the entire battle is fought to free her. She represents purity, loyalty, and the object of the hero''s virtue.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 8, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who is the Bula?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Why is the Bula important?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Bula is important because she is the reason for the entire conflict, the whole sword dance is fought over her. Her steadfast refusal to yield to her captor (","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"\"far more pain for me is your unwanted love than the steel\"","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":") sets the moral stakes: the battle is about honour and loyalty, not just possession. Her liberation at the end marks the triumph of virtue.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 9, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Why is the Bula important?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who is the Bula''s fiancé?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Bula''s fiancé is Osman, the White King. He arrives to reclaim his betrothed from Moro, who has abducted her, and his army wins the battle that frees her.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 10, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who is the Bula''s fiancé?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who is Moro?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Moro is the Black King and the abductor in the Moreška. He is the son of Otmanović, and he has taken the Bula by force and tries to win her affection. His army loses the seven battles, and he ends by surrendering his sword at the White King''s feet.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 11, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who is Moro?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who is Otmanović?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Otmanović is Moro''s father in the Moreška, a figure of dynastic authority who represents the weight of the enemy army behind his son. He is not himself the Black King; that is Moro.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 12, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who is Otmanović?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who is Osman?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Osman is the White King and the hero of the Moreška. He is the Bula''s betrothed and wears red; he represents justice and the rightful lover, and his army always wins, freeing the Bula.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 13, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who is Osman?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Why is the Bula in chains?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Bula is in chains because she has been abducted and held captive by Moro, the Black King. The performance opens with Moro dragging the chained Bula and trying to win her love, while she refuses; she is freed from her chains only at the end, after the White King''s army wins.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 14, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Why is the Bula in chains?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Which king wins in the end?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The White King, Osman, always wins. The White army (which wears red) defeats the Black army; Moro surrenders his sword at Osman''s feet, and the Bula is freed from her chains. The ending never changes, virtue always wins.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'story'::enum_faqs_category, 'en'::enum_faqs_locale, 15, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Which king wins in the end?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška dynamic?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška is highly dynamic. It is a physically intense sword dance in which the combat escalates across seven figures from lyrical circling to a furious, full-speed finale, with iron swords clashing hard enough to throw sparks. The dancers sustain high-energy movement throughout, making it as much an athletic feat as a performance.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 16, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška dynamic?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Are the swords in the Moreška real?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the swords are real iron, not props. Each weighs about one kilogram, and the dancers strike them together hard enough to produce sparks and a ringing ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"\"bam bam bam\"","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" that echoes off the stone walls of the old town. The double-sword technique, a blade in each hand, is what sets the Moreška apart from other European sword dances.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 17, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Are the swords in the Moreška real?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How heavy are the swords?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Each sword weighs about one kilogram of iron, and every dancer wields two of them, one in each hand. Historically (until the 1960s) the two swords were of unequal length: a longer one in the right hand for attack and a shorter one in the left for defence.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 18, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How heavy are the swords?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'What is the *sfida*?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"sfida","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" is the challenge that opens the sword dance. The Black King dances alone, a graceful but menacing solo in 6/8 rhythm, to provoke the White King. It is a kinetic declaration of war that leads directly into the entry of both armies and the seven battles.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 19, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'What is the *sfida*?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How many dance figures does the Moreška have?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška has ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"seven","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" main figures, called ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"kolapi","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", preceded by the opening ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"sfida","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (the challenge). Each figure has a traditional name, Rugier, Moreška, Finta, Moro in dentro, Križ (the Cross), Rugier de fuorivia, and the Final Figure, and they escalate in tempo to a furious finale in 4/4 time.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 20, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How many dance figures does the Moreška have?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'What colours are the two opposing armies?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The two armies are the \"White\" army and the \"Black\" army. Notably, the White army wears ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"red","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", and the Black army wears ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"black","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". The White (red) army represents justice and the rightful claimant, and always wins.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 21, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'What colours are the two opposing armies?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Do dancers ever get injured performing the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška uses real iron swords, so injuries can happen, the dancers accept that as part of a genuine war dance, but they are kept rare by training: dancers strike with enough precision to avoid serious harm while still clashing hard enough to satisfy a real war dance. That balance comes from months of disciplined practice.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 22, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Do dancers ever get injured performing the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška dangerous?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška is performed with real iron swords and full-contact strikes, so it demands skill and discipline, but it is carefully controlled. The dancers train for months to strike precisely, so the danger is real yet managed; what looks like a fierce battle is a tightly rehearsed routine. Injuries can occasionally happen and are accepted as part of the tradition.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dance'::enum_faqs_category, 'en'::enum_faqs_locale, 23, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška dangerous?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška performed with musical accompaniment?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the Moreška is performed to a live brass-band score that underscores every clash of the swords and every turn in the story. The music intensifies along with the seven battles, building from lyrical themes to a high-tempo, percussive finale.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'music'::enum_faqs_category, 'en'::enum_faqs_locale, 24, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška performed with musical accompaniment?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who wrote the music for the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The music was composed by the renowned Croatian composer ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Krsto Odak","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" in 1937, in collaboration with conductor ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Josip Svoboda","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". Their brass-band arrangement has been used at every performance since 1947 and is still the score you hear today. The original score was lost during the Second World War and later restored with Odak''s own help, which is why it has been in continuous use since 1947.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'music'::enum_faqs_category, 'en'::enum_faqs_locale, 25, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who wrote the music for the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the accompanying music performed live?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the music is played live by the Wind Orchestra of HGD Sveta Cecilija at every performance. The orchestra is the musical backbone of the Moreška, performing Krsto Odak''s 1937 brass arrangement in real time alongside the dancers.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'music'::enum_faqs_category, 'en'::enum_faqs_locale, 26, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the accompanying music performed live?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'What language is the Moreška performed in?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška''s scripted dialogue is spoken in an ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"archaic 17th-century Korčulan dialect","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" of Croatian, which connects the performance to its medieval roots. For visitors, a spoken introduction and summary are given in ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Croatian and English","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", and much of the show is told through music, dance, and action, so it can be followed without understanding every word.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'music'::enum_faqs_category, 'en'::enum_faqs_locale, 27, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'What language is the Moreška performed in?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Where is the Moreška performed?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška is performed in Korčula''s old town at the open-air ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Summer Cinema","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" (Ljetno kino), in the heart of the medieval town. Performances start at ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"21:00","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". If the weather is bad, the show moves indoors to Centar za kulturu Korčula.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 28, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Where is the Moreška performed?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How long is a Moreška performance?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"A Moreška evening lasts ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"about one hour (roughly 60 minutes)","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" including the other sections'' contributions. It has three parts: an opening of Dalmatian ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"klapa","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" singing and orchestra, the spoken dramatic prologue, and then the seven sword battles. ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"(The historic St. Theodore presentation could run up to two hours; the sword-dance portion itself is up to ~30 minutes.)","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 29, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How long is a Moreška performance?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Do you buy tickets for the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, you buy tickets for the public Moreška performances. Tickets are ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"€20 for adults","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" and ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"€10 for children under 14","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", and can be booked online at moreska.eu. For groups, every fifth ticket is free.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 30, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Do you buy tickets for the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Where is the Moreška held if it rains?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"In bad weather the Moreška moves from the open-air Summer Cinema to an indoor venue, ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Centar za kulturu Korčula","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". The performance still goes ahead, the change is only the location.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 31, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Where is the Moreška held if it rains?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Is the Moreška performed only in summer?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The public Moreška performances run through the warmer season, usually from May to October, staged on selected evenings at 21:00. Historically the dance was performed only once a year, on 29 July; the schedule was expanded to multiple shows a week to accommodate visitors.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 32, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Is the Moreška performed only in summer?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Can you meet the moreškanti after the performance?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, visitors are welcome to meet the performers after the show. You can be photographed with the two kings and the Bula, and you''re welcome to join the society for a drink at its premises. It''s a relaxed way to round off the evening and hear a little more about the tradition.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 33, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Can you meet the moreškanti after the performance?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Can you take photos with the moreškanti after the performance?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, after the performance you can take photos with the two kings and the Bula in costume. It''s a popular way to remember the show, and the performers are happy to pose with visitors.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'visiting'::enum_faqs_category, 'en'::enum_faqs_locale, 34, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Can you take photos with the moreškanti after the performance?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Who performs the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška is performed by the people of Korčula, traditionally local men from Korčulan families, organised by the cultural society HGD Sveta Cecilija. It is not a touring cast: the dancers are members of the community, and roles like the kings and the Bula are often passed from father to son.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 35, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Who performs the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Are the moreškanti professional dancers?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"No, the moreškanti are not professional dancers. They are members of the Korčula community who learn the dance from childhood and perform as part of the cultural society HGD Sveta Cecilija. Their skill comes from years of local tradition, not professional dance careers, which is part of what makes the Moreška authentic.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 36, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Are the moreškanti professional dancers?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How much practice does it take to dance ("batit") the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Learning to perform the Moreška (\"batit\") takes roughly ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"10 months to a year and a half","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" of training. In that time a newcomer builds up the swordsmanship, stamina, and precise timing the dance demands, especially the double-sword technique, striking hard enough to spark while staying safe. Many dancers grow up around the tradition and it is often passed from father to son, but the focused training to be stage-ready is measured in months, not years.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 37, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How much practice does it take to dance ("batit") the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How many moreškanti take part in a performance?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The number varies with turnout, but each side typically fields between ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"6 and 12 pairs of dancers","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", rising to as many as ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"15 per side for the grandest performances","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", and the two kings and Otmanović are counted among those dancers. Add the Bula, the torchbearers, the live ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Wind Orchestra (around 20 musicians)","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" and the ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"Klapa Sveta Cecilija vocal ensemble (usually 5–8 singers)","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", and a full Moreška evening brings dozens of performers together on stage. The society itself has around 150 members across its three sections.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 38, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How many moreškanti take part in a performance?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'How do young people learn the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Young people in Korčula learn the Moreška from childhood, boys begin learning the steps in elementary school, and the tradition is passed down through families, often from father to son. Stepping into the troupe is seen as a marker of adulthood and civic pride, which keeps the dance alive across generations.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 39, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'How do young people learn the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Do children also perform the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Yes, the most prepared young dancers do step into public performances when they are ready and when the cast needs them. Children are central to keeping the Moreška alive: they begin learning the steps young, and the post-war revival of 1944 was itself built by training teenagers aged 12 to 17. Those who have mastered the choreography perform alongside the adults as required.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'dancers'::enum_faqs_category, 'en'::enum_faqs_locale, 40, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Do children also perform the Moreška?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'When was the Moreška first mentioned in Korčula?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The first unambiguous written record of the Moreška in Korčula is a town journal entry dated ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"7 March 1666","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", describing a carnival performance. By then the dance was already woven into the life of the town. Its wider Mediterranean origins go back much further, to a recorded performance in Lérida, Spain, in 1150.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'history'::enum_faqs_category, 'en'::enum_faqs_locale, 41, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'When was the Moreška first mentioned in Korčula?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'When is the most ceremonial Moreška performance?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The most ceremonial performance traditionally takes place on ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"29 July, the Feast of St. Theodore","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", Korčula''s patron saint. Historically this was the one performance of the year, a lavish presentation that could last up to two hours. ","type":"text","version":1},{"detail":0,"format":2,"mode":"normal","style":"","text":"(Note: the St. Theodore show is a special performance, not one of the regular public ticketed shows.)","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'history'::enum_faqs_category, 'en'::enum_faqs_locale, 42, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'When is the most ceremonial Moreška performance?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Why did the Moreška survive only in Korčula?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška survived only in Korčula while it died out elsewhere in the Mediterranean, and scholars offer three main explanations: it doubled as ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"martial training","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" for a small island garrison often raided by pirates and Ottomans; it served as a ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"\"hidden transcript\" of resistance","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":", letting locals symbolically defy foreign rulers; and the town''s tight system of ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"guilds and brotherhoods","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":" gave it the social stability to pass complex choreography from father to son across centuries.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'history'::enum_faqs_category, 'en'::enum_faqs_locale, 43, 'published'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Why did the Moreška survive only in Korčula?' AND locale = 'en');

INSERT INTO faqs (question, answer, category, locale, "order", status)
SELECT 'Which countries has HGD Sveta Cecilija toured with the Moreška?', '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The Moreška has represented Korčula on the international stage, including a performance at the ","type":"text","version":1},{"detail":0,"format":1,"mode":"normal","style":"","text":"1947 World Youth Festival in Prague","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":". A guide member also mentioned appearances in Spain, France, Albania and Italy, but that list is unconfirmed, do not publish it until issue #340 returns a verified list (which will also seed a candidate 7th blog post, \"Moreška around the world\").","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'::jsonb, 'history'::enum_faqs_category, 'en'::enum_faqs_locale, 44, 'draft'::enum_faqs_status
WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = 'Which countries has HGD Sveta Cecilija toured with the Moreška?' AND locale = 'en');
