import { describe, it, expect, vi } from 'vitest'
import { sendTicketEmail, type SendTicketEmailDeps } from './send-ticket-email'

function makeInput(overrides: Record<string, unknown> = {}) {
  return {
    orderId: '1247',
    buyer: { name: 'Ana Anić', email: 'ana@example.com' },
    show: {
      date: '2026-07-15',
      time: '21:00',
      venue: 'ljetno-kino' as const,
    },
    order: { adultCount: 2, childCount: 1, total: 5000 },
    tokens: ['tok_a', 'tok_b', 'tok_c'],
    locale: 'en' as const,
    ...overrides,
  }
}

function makeDeps(overrides: Partial<SendTicketEmailDeps> = {}): SendTicketEmailDeps {
  return {
    fetch: vi.fn().mockResolvedValue(new Response('{}', { status: 201 })),
    generateQrPng: vi.fn().mockResolvedValue(Buffer.from('fake-png')),
    brevoApiKey: 'test-key',
    renderTicketsPdf: vi.fn().mockResolvedValue(Buffer.from('%PDF-1.3 fake-pdf-bytes')),
    renderTicketEmail: vi.fn().mockResolvedValue({
      html: '<html><body>Hi Ana, Summer Cinema 2026-07-15 21:00 €50.00 adult child</body></html>',
      subject: 'Your Moreška tickets - Wednesday, 15 July 2026',
    }),
    ...overrides,
  }
}

describe('sendTicketEmail', () => {
  it('POSTs to Brevo transactional email endpoint with api-key header', async () => {
    const deps = makeDeps()
    await sendTicketEmail(makeInput(), deps)

    expect(deps.fetch).toHaveBeenCalledTimes(1)
    const [url, init] = (deps.fetch as ReturnType<typeof vi.fn>).mock.calls[0]
    expect(url).toBe('https://api.brevo.com/v3/smtp/email')
    expect(init.method).toBe('POST')
    expect(init.headers['api-key']).toBe('test-key')
    expect(init.headers['content-type']).toBe('application/json')
  })

  it('sends from tickets@moreska.eu with Reply-To info@ to the buyer with the rendered subject', async () => {
    const deps = makeDeps()
    await sendTicketEmail(makeInput(), deps)

    const [, init] = (deps.fetch as ReturnType<typeof vi.fn>).mock.calls[0]
    const body = JSON.parse(init.body)
    expect(body.sender.email).toBe('tickets@moreska.eu')
    expect(body.replyTo.email).toBe('info@moreska.eu')
    expect(body.to).toEqual([{ email: 'ana@example.com', name: 'Ana Anić' }])
    expect(body.subject).toMatch(/Moreška/)
  })

  it('attaches a single PDF named moreska-tickets-{date}.pdf, generated by renderTicketsPdf', async () => {
    const deps = makeDeps()
    await sendTicketEmail(makeInput(), deps)

    expect(deps.renderTicketsPdf).toHaveBeenCalledTimes(1)
    const pdfCallArgs = (deps.renderTicketsPdf as ReturnType<typeof vi.fn>).mock.calls[0]
    expect(pdfCallArgs[0].tokens).toEqual(['tok_a', 'tok_b', 'tok_c'])
    expect(pdfCallArgs[0].orderRef).toBe('1247')
    expect(pdfCallArgs[0].locale).toBe('en')

    const [, init] = (deps.fetch as ReturnType<typeof vi.fn>).mock.calls[0]
    const body = JSON.parse(init.body)
    expect(body.attachment).toHaveLength(1)
    expect(body.attachment[0].name).toBe('moreska-tickets-2026-07-15.pdf')
    expect(Buffer.from(body.attachment[0].content, 'base64').toString()).toBe(
      '%PDF-1.3 fake-pdf-bytes',
    )
  })

  it('passes the rendered HTML through to Brevo verbatim', async () => {
    const deps = makeDeps()
    await sendTicketEmail(makeInput(), deps)

    const [, init] = (deps.fetch as ReturnType<typeof vi.fn>).mock.calls[0]
    const body = JSON.parse(init.body)
    expect(body.htmlContent).toContain('Summer Cinema')
    expect(body.htmlContent).toContain('Ana')
  })

  it('passes locale and order ref through to both renderers', async () => {
    const deps = makeDeps()
    await sendTicketEmail(makeInput({ locale: 'hr', orderId: '9001' }), deps)

    const emailCall = (deps.renderTicketEmail as ReturnType<typeof vi.fn>).mock.calls[0][0]
    expect(emailCall.locale).toBe('hr')
    expect(emailCall.orderRef).toBe('9001')

    const pdfCall = (deps.renderTicketsPdf as ReturnType<typeof vi.fn>).mock.calls[0][0]
    expect(pdfCall.locale).toBe('hr')
    expect(pdfCall.orderRef).toBe('9001')
  })

  it('resolves (does not throw) when Brevo returns an error response', async () => {
    const deps = makeDeps({
      fetch: vi
        .fn()
        .mockResolvedValue(new Response('{"message":"invalid"}', { status: 400 })),
    })
    await expect(sendTicketEmail(makeInput(), deps)).resolves.toBeUndefined()
  })

  it('resolves (does not throw) when fetch itself rejects', async () => {
    const deps = makeDeps({
      fetch: vi.fn().mockRejectedValue(new Error('network down')),
    })
    await expect(sendTicketEmail(makeInput(), deps)).resolves.toBeUndefined()
  })

  it('resolves (does not throw) when PDF rendering throws', async () => {
    const deps = makeDeps({
      renderTicketsPdf: vi.fn().mockRejectedValue(new Error('font load failed')),
    })
    await expect(sendTicketEmail(makeInput(), deps)).resolves.toBeUndefined()
    expect(deps.fetch).not.toHaveBeenCalled()
  })

  it('failure logs include orderId, buyer email and token count for manual recovery', async () => {
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
    const deps = makeDeps({
      fetch: vi.fn().mockResolvedValue(new Response('boom', { status: 503 })),
    })
    await sendTicketEmail(makeInput({ orderId: 'order_99' }), deps)
    const logged = errSpy.mock.calls.flat().join(' ')
    expect(logged).toContain('orderId=order_99')
    expect(logged).toContain('email=ana@example.com')
    expect(logged).toContain('tokens=3')
    expect(logged).toContain('status=503')
    errSpy.mockRestore()
  })
})
